### ISSUE TITLE
Forking this repo

### ISSUE THREAD

**Issue by JuanTamadski** [acastillorobles77/device_xiaomi_vayu#1]
Hi @acastillorobles77 can I fork this repo and do some building in cirrus. I'll always credit your trees if ever I release a rom publicly. It is also okay if you don't want to. I'm just asking for some permissions

**Comment by acastillorobles77** [comment]
Hi, yes you can fork and use this repo; but please keep in mind that this device tree is not made by me, it is based on ArrowOS trees as shown on Readme.
